### ISSUE TITLE
GitHub Actions are not enabled

### ISSUE THREAD

**Issue by szepeviktor** [Spomky/Spomky#5]
@Spomky https://github.com/Spomky/Spomky/actions 👀

**Comment by Spomky** [comment]
Hi,

Actions are enabled (otherwise the tab is missing).
I guess this is because no workflows have been run yet.

Regards.

**Comment by szepeviktor** [comment]
This commit was a "push". I expected CI to run.

https://github.com/Spomky/Spomky/commit/6c5f54b49cd9202e4efce7f5dbcb550d3565f215
